# lua_code_cache on;
# lua_package_path '/opt/soft/lualib/?.lua;/opt/soft/lualib/resty/core/?.lua;;';
# lua_package_cpath '/opt/soft/lualib/?.so;;';
# init_by_lua_file  '/opt/soft/lua_ngx/mycool_init.lua';
