log_format main
    '$remote_addr $server_addr $host $server_port - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" "$http_user_agent" '
    '$upstream_addr $request_time $upstream_response_time';

access_log  logs/access.log  main;
error_log   logs/error.log   warn;
